apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-proxy
  name: auth-proxy
  namespace: istio-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: auth-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-proxy
  name: auth-proxy-ds
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-proxy
  template:
    metadata:
      labels:
        app: auth-proxy
    spec:
      containers:
        - image: knabben/proxy:latest
          imagePullPolicy: IfNotPresent
          name: auth-proxy
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            privileged: false
